CREATE DATABASE LINK BRANCH_1 CONNECT TO TROFIV IDENTIFIED BY passwd USING
  '(DESCRIPTION=
    (ADDRESS=
     (PROTOCOL=TCP)
     (HOST=1.oracle.trofiv.io)
     (PORT=1521))
    (CONNECT_DATA=
     (SID=ORCLCDB)))';
CREATE DATABASE LINK BRANCH_2 CONNECT TO TROFIV IDENTIFIED BY passwd USING
  '(DESCRIPTION=
    (ADDRESS=
     (PROTOCOL=TCP)
     (HOST=2.oracle.trofiv.io)
     (PORT=1521))
    (CONNECT_DATA=
     (SID=ORCLCDB)))';

CREATE TABLE CUSTOMERS_STORE (
  CHANGED_AT   TIMESTAMP    NOT NULL,
  CUSTOMER_ID  RAW(32)      NOT NULL,
  STATUS       CHAR(1)      NOT NULL,
  FIRST_NAME   VARCHAR2(35) NOT NULL,
  LAST_NAME    VARCHAR2(35) NOT NULL,
  MIDDLE_NAME  VARCHAR2(35) NOT NULL,
  EMAIL        VARCHAR2(45) NOT NULL,
  PHONE_NUMBER VARCHAR2(15) NOT NULL,
  PRIMARY KEY (CUSTOMER_ID, CHANGED_AT)
);

CREATE TABLE PROCUREMENTS_STORE (
  CHANGED_AT     TIMESTAMP NOT NULL,
  PROCUREMENT_ID RAW(32)   NOT NULL,
  STATUS         CHAR(1)   NOT NULL,
  ITEM_ID        RAW(32)   NOT NULL,
  PRICE          NUMERIC(15, 2),
  AMOUNT         NUMERIC(7, 0),
  TIME           TIMESTAMP,
  PRIMARY KEY (PROCUREMENT_ID, CHANGED_AT)
);

CREATE TABLE SALES_STORE (
  CHANGED_AT  TIMESTAMP NOT NULL,
  SALE_ID     RAW(32)   NOT NULL,
  STATUS      CHAR(1)   NOT NULL,
  ITEM_ID     RAW(32)   NOT NULL,
  CUSTOMER_ID RAW(32)   NOT NULL,
  AMOUNT      NUMERIC(4, 0),
  TIME        TIMESTAMP,
  TOTAL_PRICE NUMERIC(15, 2),
  PRIMARY KEY (SALE_ID, CHANGED_AT)
);

CREATE TABLE ITEMS_STORE (
  CHANGED_AT   TIMESTAMP      NOT NULL,
  ITEM_ID      RAW(32)        NOT NULL,
  STORE_NUMBER NUMERIC(1, 0)  NOT NULL,
  STATUS       CHAR(1)        NOT NULL,
  VENDOR_CODE  NUMERIC(32, 0) NOT NULL,
  NAME         VARCHAR2(255)  NOT NULL,
  DESCRIPTION  VARCHAR2(4000) NOT NULL,
  PRICE        NUMERIC(15, 2) NOT NULL,
  PRIMARY KEY (ITEM_ID, STORE_NUMBER, CHANGED_AT)
);

CREATE TABLE PROMOTIONS_STORE (
  CHANGED_AT   TIMESTAMP     NOT NULL,
  PROMOTION_ID RAW(32)       NOT NULL,
  STATUS       CHAR(1)       NOT NULL,
  VALID_FROM   TIMESTAMP     NOT NULL,
  VALID_TO     TIMESTAMP     NOT NULL,
  DISCOUNT_PCT NUMERIC(2, 0) NOT NULL,
  PRIMARY KEY (PROMOTION_ID, CHANGED_AT)
);

CREATE TABLE REALIZATIONS_STORE (
  CHANGED_AT     TIMESTAMP      NOT NULL,
  REALIZATION_ID RAW(32)        NOT NULL,
  STATUS         CHAR(1)        NOT NULL,
  GOOD_ID        RAW(32)        NOT NULL,
  PROMOTION_ID   RAW(32)        NOT NULL,
  PRICE          NUMERIC(15, 2) NOT NULL,
  PRIMARY KEY (REALIZATION_ID, CHANGED_AT)
);

CREATE TABLE GOODS_TO_PROMOTIONS_STORE (
  CHANGED_AT   TIMESTAMP NOT NULL,
  GOOD_ID      RAW(32)   NOT NULL,
  PROMOTION_ID RAW(32)   NOT NULL,
  STATUS       CHAR(1)   NOT NULL,
  PRIMARY KEY (GOOD_ID, PROMOTION_ID, CHANGED_AT)
);