CREATE TABLE GOODS (
  GOOD_ID     RAW(32) DEFAULT SYS_GUID() NOT NULL,
  VENDOR_CODE NUMERIC(32, 0)             NOT NULL,
  NAME        VARCHAR(255)               NOT NULL,
  DESCRIPTION VARCHAR2(4000)             NOT NULL,
  BASE_PRICE  NUMERIC(15, 2)             NOT NULL,
  PRIMARY KEY (GOOD_ID),
  CONSTRAINT GOOD_UNIQ_VENDOR_CODE_IDX UNIQUE (VENDOR_CODE)
);

CREATE TABLE PROMOTIONS (
  PROMOTION_ID RAW(32) DEFAULT SYS_GUID() NOT NULL,
  VALID_FROM   TIMESTAMP                  NOT NULL,
  VALID_TO     TIMESTAMP                  NOT NULL,
  DISCOUNT_PCT NUMERIC(2, 0)              NOT NULL,
  PRIMARY KEY (PROMOTION_ID)
);

CREATE INDEX PROMOTION_VALID_FROM_IDX
  ON PROMOTIONS (VALID_FROM);
CREATE INDEX PROMOTION_VALID_TO_IDX
  ON PROMOTIONS (VALID_TO);

CREATE TABLE GOODS_TO_PROMOTIONS (
  GOOD_ID      RAW(32) NOT NULL,
  PROMOTION_ID RAW(32) NOT NULL,
  PRIMARY KEY (GOOD_ID, PROMOTION_ID),
  CONSTRAINT GOOD_TO_PROMOTION_GOOD_FK FOREIGN KEY (GOOD_ID) REFERENCES GOODS (GOOD_ID) ON DELETE CASCADE,
  CONSTRAINT GOOD_TO_PROMOTION_PROMOTION_FK FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTIONS (PROMOTION_ID) ON DELETE CASCADE
);

CREATE TABLE REALIZATIONS (
  REALIZATION_ID RAW(32) DEFAULT SYS_GUID() NOT NULL,
  GOOD_ID        RAW(32)                    NOT NULL,
  PROMOTION_ID   RAW(32)                    NOT NULL,
  PRICE          NUMERIC(15, 2)             NOT NULL,
  PRIMARY KEY (REALIZATION_ID),
  CONSTRAINT REALIZATION_GOOD_FK FOREIGN KEY (GOOD_ID) REFERENCES GOODS (GOOD_ID) ON DELETE CASCADE,
  CONSTRAINT REALIZATION_PROMOTION_FK FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTIONS (PROMOTION_ID) ON DELETE CASCADE
);